### ISSUE TITLE
Plotting

### ISSUE THREAD

**Issue by ghost** [trinker/numform#23]
Hi,

I'm trying to use the package but I must be doing something wrong. I don't understand how to format the plots 😅

I'm working with some Google Analytics data (so it's not reproducible but pretty straightforward I hope). 

```R
ga %>%
  filter(device_category == "mobile" & operating_system %in% c("Android", "iOS")) %>%
  group_by(operating_system) %>%
  summarise(total_pageviews = f_mills(sum(pageviews))) %>%
  kable()
```
Works as expected

<img width="250" alt="screen shot 2018-12-04 at 09 40 04" src="https://user-images.githubusercontent.com/8994002/49429383-a3d4d180-f7a8-11e8-8862-bccb7dd49d8d.png">

But then this

```R
ga %>%
  filter(device_category == "mobile" & operating_system %in% c("Android", "iOS")) %>%
  group_by(operating_system) %>%
  summarise(total_pageviews = f_mills(sum(pageviews))) %>%
  ggplot(aes(operating_system, total_pageviews)) +
  geom_col()
```
Gives me this

<img width="714" alt="screen shot 2018-12-04 at 09 41 55" src="https://user-images.githubusercontent.com/8994002/49429504-de3e6e80-f7a8-11e8-80b4-0cf9dea4d434.png">

I understand that it's because the formatted data is actually a character but I wonder how one should pipe the formatting into the pipes?

When I try

```R
ga %>%
  filter(device_category == "mobile" & operating_system %in% c("Android", "iOS")) %>%
  group_by(operating_system) %>%
  summarise(total_pageviews = sum(pageviews)) %>%
  ggplot(aes(operating_system, total_pageviews)) +
  scale_y_continuous(labels = ff_denom()) +
  geom_col()
```
I get a warning

<img width="412" alt="screen shot 2018-12-04 at 09 43 33" src="https://user-images.githubusercontent.com/8994002/49429582-180f7500-f7a9-11e8-83d5-43c329d59d4c.png">

And this resulting plot

<img width="711" alt="screen shot 2018-12-04 at 09 43 52" src="https://user-images.githubusercontent.com/8994002/49429597-278ebe00-f7a9-11e8-8b9c-1a0223ba9fa6.png">

Here's my sessionInfo:
R version 3.5.1 (2018-07-02)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS High Sierra 10.13.6

(I hope I was clear). Thanks for any help.

**Comment by trinker** [comment]
Hi @xslates,

Thanks for raising this.  It makes it useful if you indeed produce a minimal working example.  In this case making it reproducable required a couple lines of code to make a 2 x 2 dataframe as I show below and add in the library call to load ggplot and dplyr (no need for the group_by + summary as these are not partof the problem and add non-essential code to reproducing the error).  This makes it so others can run the code in issues and solve their own problems.

The last use that you are using is the correct approach.  The issue is happening because you have scientific notation on.  You can turn it off by using `options(scipen = 999)`:

```
library(numform)
library(ggplot2)
library(dplyr)

ga <- data_frame(
    total_pageviews =  c(96789789, 135111111),
    operating_system = c("Android", "iOS")
)

options(scipen=999)

ga %>%
  ggplot(aes(operating_system, total_pageviews)) +
  scale_y_continuous(labels = ff_denom()) +
  geom_col()
```

Results in:

![image](https://user-images.githubusercontent.com/1763278/49442654-2b661480-f798-11e8-9df4-7e9010dda515.png)

That being said I can reproduce the issue by setting `options(scipen=0)`.  This feels like something `f_denom` should handle or at the very least detect and warn about.

**Comment by trinker** [comment]
Potential approaches to handling (change OR warn)

```
options(scipen=0)

testing <- function(){

    print(options()[['scipen']])

    scipen <- options()[['scipen']]
    if (scipen < 12) {
        warning(paste(
            "Scientific notation is likely to be used, resulting in poor output(s)\n",
            sprintf("Currently your setting is: `options(scipen = %s)`\n", scipen),
            "Use `options(scipen = 999)` to ensure proper formatting"
        ))
    }

    on.exit(options(scipen = scipen))    
    options(scipen = 999)

    print(options()[['scipen']])

    stop()
}

testing()
print(options()[['scipen']])
```

## Results In:

```
> testing()
[1] 0
[1] 999
Error in testing() : 
In addition: Warning message:
In testing() :
  Scientific notation is likely to be used, resulting in poor output(s)
 Currently your setting is: `options(scipen = 0)`
 Use `options(scipen = 999)` to ensure proper formatting
> print(options()[['scipen']])
[1] 0
```

**Comment by ghost** [comment]
Thank you so much! That’s golden

**Comment by trinker** [comment]
Another possibility:

```
drop_sci_note <- function(x, ...){

    x <- as.character(as.numeric(x))
    locs <- grepl('e\\+', x)
    x[locs] <- paste0(
        gsub('e\\+.+', '', x[locs]), 
        unlist(lapply(gsub('^.+?e\\+', '', x[locs]), function(x){paste(rep('0', x), collapse = '')}))
    )
    x
}
```

From https://github.com/trinker/textclean/blob/master/R/utils.R

**Comment by trinker** [comment]
The following now gives the expected result:

```
library(numform)
library(ggplot2)
library(dplyr)

ga <- data_frame(
    total_pageviews =  c(96789789, 135111111),
    operating_system = c("Android", "iOS")
)

options(scipen=0)

ga %>%
  ggplot(aes(operating_system, total_pageviews)) +
  scale_y_continuous(labels = ff_denom()) +
  geom_col()
```

Thanks again for raising the issue.
