### ISSUE TITLE
Adding the option in f_num to keep the leading zero

### ISSUE THREAD

**Issue by dcbrh** [trinker/numform#25]
Hello!

I thought it would be a good idea to have an argument which would allow users to keep the leading zero in the f_num function - some might want to edit the digit number, but have the zero because the variable value can in theory go over 1. 

This is just a suggestion, and the code change would be minor...

Cheers!

**Comment by trinker** [comment]
This should be possible in version 0.6.7

```
> f_num(0.4)
[1] ".4"

> f_num(0.4, retain.leading.zero=TRUE)
[1] "0.4"
```
