### ISSUE TITLE
Add support for kable and kableExtra when escape=F

### ISSUE THREAD

**Issue by csnydermph** [trinker/numform#26]
The default behavior of `f_percent()` will return a character vector with trailing %'s as intended, however, this vector cannot be processed by R Markdown when using the `kable()` function if using `kable(escape=F)`, as the `%` is an escape character inside of LaTeX ([source](https://tex.stackexchange.com/questions/34580/escape-character-in-latex)). When using `f_percent()` to generate values for a kable where `kable(escape=F)`, LaTeX will escape at the `%` and will error out and halt.

For this use-case, LaTeX needs to be passed a vector with a `%` that is *escaped out for LaTeX*, which means that R has to pass to LaTeX a vector with trailing `/%'s.

Support for `kable(escape=F)` can be achieved with the following method, for example by borrowing from your function, adding an argument to allow normal and escape-ready formatting by implementing:

`f_percent = function(x, digits = getOption("numformdigits"), less.than.replace = FALSE, kable.escape = TRUE, ...) {`
  `if (kable.escape == TRUE) {out = f_num(x, digits = digits, s="%", ...)}`
  `if (kable.escape == FALSE) {out = f_num(x, digits = digits, s = paste("\\", "%", sep=""), ...)}`
  ` if (isTRUE(less.than.replace)){`
`    if (is.null(digits)) digits = 1`
`    repl = replace_less_than(digits, percent = TRUE)`
`    out[x < repl[['prop_cut']][1] & x >= 0] = repl[['replacement']][1]`
`    out[x > repl[['prop_cut']][2] & x < 0] = repl[['replacement']][2]`
`  }`
`  out`
`}`

R will escape from the first \ in `\\` pasting a single `\` to each item in vector `x`, followed by pasting a `%` to each item in vector `x`. It must be done in this order as R views `\%` as an unrecognized escape in character strings, and pasting `\\%` will add this unrecognized escape instead. Trying to use `gsub()` will result in either too many or too few escapes in testing.

This change will allow the use of escaped characters and the numform package in the same kable, to generate tables with, for example, percent formatted columns concurrent with columns using f_num and f_comma, and column names with multiple rows( which require the use of `kable(escape=F)`), reference image below of some US Census Data with these features co-occuring, using the updated function demonstrated above:

![image](https://user-images.githubusercontent.com/29576181/103355825-468dd600-4a7d-11eb-88e1-6a02ef3b5223.png)

You may also want to add escape support for `f_dollar()` , as `$` is also a LaTeX escape character.

**Comment by trinker** [comment]
Thanks for the suggestions.  This has been added by setting `s` (suffix) or `p`  (prefix) explicitly.  This is more generalizable.

**Comment by csnydermph** [comment]
Apologies for Re-opening. Wanted to bring to your attention errors using the above method, at least for some use-cases.

In testing for `f_dollar` and `f_percent`, this solution returns an error, due to attempting to pass duplicate "p" or "s" values to the baked-in `f_num` call. The `p` and `s` arguments appear only to pass correctly when using `f_num`. Wanted to confirm that this is intended behavior, and it is known that the wrapper functions do not accept these arguments, or am I misunderstanding a component of the package.

Reprex:
`f_dollar(c(5.50, 100.1, 7))` Returns to stdout correctly.
`f_dollar(c(5.50, 100.1, 7), p = "\\$")` Returns with an error: Formal argument "p" matched by multiple actual arguments
`f_num(c(5.50, 100.1, 7), p = "\\$", digits = 2)` Returns what was expected from the wrapper when attempting to run the above.


Thanks again.

**Comment by trinker** [comment]
Can you share exactly what you get if you run the following?

```
utils::packageVersion('numform')
numform::f_dollar(c(5.50, 100.1, 7), p = "\\$")
```

This is my output:

![image](https://user-images.githubusercontent.com/1763278/139584916-a0de8bcd-2abe-4b34-9b22-c17128d9cca9.png)

**Comment by csnydermph** [comment]
Version Was 0.6.4.

Updating to 0.7.0 has resolved the issue.

Thanks much!
